//
//  Constants.swift
//  FooD
//
//  Created by LAURA JELENICH on 2/26/19.
//  Copyright © 2019 LAURA JELENICH. All rights reserved.
//

import Foundation

class Constants {
    
    //    https://www.luby.info/2015/02/15/swift-constants-files.html
    
    static let Users = "users"
    static let Uid = "uid"
    static let ChefUid = "chefUid"
    static let UserUid = "userUid"
    static let Id = "id"
    static let Key = "key"
    static let Email = "email"
    static let Username = "username"
    static let Name = "name"
    static let ProfileImageUrl = "profileImageUrl"
    static let ProfileBannerUrl = "profileBannerUrl"
    static let Location = "location"
    static let LocationShort = "locationShort"
    static let Bio = "bio"
    static let CoverImages = "Cover_Images"
    static let Archive = "archive"
    static let Blocked = "blocked"
    static let BlockedBy = "blockedBy"
    
    static let Menu = "menu"
    static let Cuisine = "cuisine"
    static let CuisineType = "cuisineType"
    static let CuisineList = "cuisineList"
    static let IsBooked = "isBooked"
    static let InvoiceSent = "invoiceSent"
    static let InvoicePaid = "invoicePaid"
    static let Bookings = "bookings"
    
    static let Detail = "detail"
    static let CourseType = "courseType"
    static let MenuType = "menuType"
    static let MenuImage = "menuImage"
    static let ImageId = "imageId"
    static let Date = "date"
    static let Time = "time"
    static let AllowsRSVP = "allowsRSVP"
    static let AllowsContact = "allowsContact"
    static let NumberOfPeople = "numberOfPeople"
    static let NumberOfCourses = "numberOfCourses"
    
    static let SharedPhotos = "shared_photos"
    static let MessageMovies = "message_movies"
    static let MessageImages = "message_images"
    static let ImageUrl = "imageUrl"
    static let EventImageUrl = "eventImageUrl"
    static let EventImages = "eventImages"
    static let VideoUrl = "videoUrl"
    static let Caption = "caption"
    static let CreationDate = "creationDate"
    static let Content = "content"
    static let Created = "created"
    static let SenderID = "senderID"
    static let Thread = "thread"
    static let RecentMessages = "recentMessages"
    
    static let Comment = "comment"
    static let Gallery = "gallery"
    static let Likes = "likes"
    static let LikeCount = "likeCount"
    static let BookmarkCount = "bookmarkCount"
    static let Bookmarks = "bookmarks"
    static let Ratings = "ratings"
    static let Rate = "rate"
    static let ReviewedUserUid = "reviewedUserUid"
    static let Stars = "stars"
    static let StarsCount = "starsCount"
    static let Messages = "messages"
    static let Message = "message"
    static let UserMessages = "user_messages"
    static let Event = "event"
    static let Events = "events"
    static let Reviews = "reviews"
    static let Review = "review"
    static let BookmarkedUsers = "bookmarkedUsers"
    static let BookmarkedUser = "bookmarkedUser"
    static let BookmarkedEvents = "bookmarkedEvents"
    static let SavedCount = "savedCount"
    
    static let PostText = "postText"
    static let Text = "text"
    static let ToId = "toId"
    static let FromId = "fromId"
    static let Timestamp = "timestamp"
    
    static let Title = "title"
    static let Note = "note"
    static let Calendar = "calendar"
    static let EventDate = "eventDate"
    static let EventDay = "eventDay"
    static let TimeStamp = "timeStamp"
    static let StartTime = "startTime"
    static let EndTime = "endTime"
    static let AvailableDate = "availableDate"
    static let Available = "available"
    static let ScheduleDate = "scheduleDate"
    static let Schedule = "schedule"
    static let BlackoutDate = "blackoutDate"
    static let Address = "address"
    static let Street = "street"
    static let Apartment = "apartment"
    static let City = "city"
    static let State = "state"
    static let Latitude = "latitude"
    static let Longitude = "longitude"
    static let ShortLocation = "shortLocation"
    
    static let Width = "width"
    static let Height = "height"
    
    static let Provider = "provider"
    
    static let Chefs = "chefs"
    static let ChefType = "chefType"
    static let IsChef = "isChef"
    static let IsNutritionist = "isNutritionist"
    static let IsPastry = "isPastry"
    static let IsVegetarian = "isVegetarian"
    static let IsVegan = "isVegan"
    static let UserRate = "userRate"
    
    static let Payments = "payments"
    static let PaymentId = "paymentId"
    static let BookingId = "bookingId"
    static let Reference = "reference"
    static let StripeAccounts = "stripe_accounts"
    static let StripeLoginLink = "stripeLoginLink"
    static let Description = "description"
    static let Amount = "amount"
    static let Invoices = "invoices"
    static let Total = "total"
    static let Fees = "fees"
    static let CustomerId = "customerId"
    static let ChefId = "chefId"
    static let Idempotency = "idempotency"
    static let CreateCharge = "createCharge"
    static let FromUser = "fromUser"
    static let ToUser = "toUser"
    static let Status = "status"
    
    
}
